import Database from "better-sqlite3";

// Open (or create) the SQLite database file (using the same file as your other controllers)
const db = new Database("game.db", { verbose: console.log });

// ───────────────────────────────
// Create the Inventory table if it does not exist.
// Columns: id is auto-incremented, playFabId links to the account, then itemId, displayName,
// catalogVersion, itemInstanceId, purchaseDate, unitPrice and annotation.
db.exec(`
  CREATE TABLE IF NOT EXISTS Inventory (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    playFabId TEXT,
    itemId TEXT,
    displayName TEXT,
    catalogVersion TEXT,
    itemInstanceId TEXT,
    purchaseDate DATETIME,
    unitPrice INTEGER,
    annotation TEXT,
    FOREIGN KEY (playFabId) REFERENCES Accounts(playFabId)
  );
`);

// ───────────────────────────────
// Interfaces
export interface InventoryItem {
  id?: number;             // Optional: auto-generated by the database on insert.
  playFabId: string;       // Identifier of the account owning this item.
  itemId: string;          // Identifier of the item (e.g., "hero_Ash")
  displayName: string;     // Human-readable name (e.g., "Cyber Girl")
  catalogVersion: string;  // Catalog version string (e.g., "Fight_001")
  itemInstanceId: string;  // Unique instance id for this specific copy of the item.
  purchaseDate: string;    // ISO string timestamp of when the item was purchased/added.
  unitPrice: number;       // Price for the item (could be 0 if free).
  annotation: string;      // Additional context or classification (e.g., "CommonSummon" or "ShardsHeroBlue")
}

// ───────────────────────────────
// Utility Functions
/**
 * createInventoryEntry
 * A utility function that creates an InventoryItem object.
 *
 * @param playFabId The owner's account ID.
 * @param itemId The item identifier.
 * @param displayName A display name for the item.
 * @param catalogVersion The catalog version string.
 * @param itemInstanceId A unique identifier for this instance of the item.
 * @param purchaseDate A Date object or string for when the item was purchased.
 * @param unitPrice The unit price (or cost) of the item.
 * @param annotation Additional annotation.
 * @returns An InventoryItem object.
 */
export function createInventoryEntry(
  playFabId: string,
  itemId: string,
  displayName: string,
  catalogVersion: string,
  itemInstanceId: string,
  purchaseDate: Date | string,
  unitPrice: number,
  annotation: string
): InventoryItem {
  return {
    playFabId,
    itemId,
    displayName,
    catalogVersion,
    itemInstanceId,
    purchaseDate: typeof purchaseDate === "string" ? purchaseDate : purchaseDate.toISOString(),
    unitPrice,
    annotation,
  };
}

// ───────────────────────────────
// Database Functions for Inventory
/**
 * addInventoryItem
 * Inserts a new inventory record into the Inventory table.
 *
 * @param item The InventoryItem to insert.
 */
export function addInventoryItem(item: InventoryItem): void {
  const stmt = db.prepare(`
    INSERT INTO Inventory (
      playFabId, itemId, displayName, catalogVersion, itemInstanceId, purchaseDate, unitPrice, annotation
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `);
  stmt.run(
    item.playFabId,
    item.itemId,
    item.displayName,
    item.catalogVersion,
    item.itemInstanceId,
    item.purchaseDate,
    item.unitPrice,
    item.annotation
  );
}

/**
 * getInventoryItems
 * Retrieves all inventory records for a given account.
 *
 * @param playFabId The owner's PlayFabId.
 * @returns An array of InventoryItem.
 */
export function getInventoryItems(playFabId: string): InventoryItem[] {
  const stmt = db.prepare(`SELECT * FROM Inventory WHERE playFabId = ?`);
  return stmt.all(playFabId) as InventoryItem[];
}

/**
 * updateInventoryItem
 * Updates an existing inventory record (by its id).
 *
 * @param id The primary key of the inventory record.
 * @param updateFields An object with the fields to update.
 */
export function updateInventoryItem(
  id: number,
  updateFields: Partial<Omit<InventoryItem, "id" | "playFabId">>
): void {
  const fields = Object.keys(updateFields);
  if (fields.length === 0) return; // Nothing to update.
  
  const setClause = fields.map(field => `${field} = ?`).join(", ");
  const stmt = db.prepare(`UPDATE Inventory SET ${setClause} WHERE id = ?`);
  const values = fields.map(field => (updateFields as any)[field]);
  values.push(id);
  stmt.run(...values);
}

/**
 * removeInventoryItem
 * Deletes an inventory record by its id.
 *
 * @param id The primary key id of the inventory record to delete.
 */
export function removeInventoryItem(id: number): void {
  const stmt = db.prepare(`DELETE FROM Inventory WHERE id = ?`);
  stmt.run(id);
}

export function clearInventoryForAccount(playFabId: string): void {
  const stmt = db.prepare(`DELETE FROM Inventory WHERE playFabId = ?`);
  stmt.run(playFabId);
}
