import { setStatistic, setUserData, setCurrency } from "../controllers/dataController";

// A function to create the default player data using your database setters.
export function createDefaultPlayerData(playFabId: string): void {
  // Default statistics array. For "LastLoginInMinutes", we calculate the value as the current time in minutes.
  const nowInMinutes = Math.floor(Date.now() / 60000);
  const defaultStatistics = [
    { statisticName: "XpLevel", value: 1, version: 0 },
    { statisticName: "ArenaPoints", value: 100, version: 3 },
    { statisticName: "ArenaPointsEven", value: 276000100, version: 0 },
    { statisticName: "BuildVersion", value: 297, version: 0 },
    { statisticName: "AvatarIndex", value: 17, version: 0 },
    { statisticName: "EventCarSmash", value: 276000000, version: 1 },
    //{ statisticName: "LastLoginInMinutes", value: nowInMinutes, version: 0 }
  ];
  
  defaultStatistics.forEach(stat => {
    // setStatistic(playFabId, statisticName, value, version) is assumed to insert/update a row in the Statistics table.
    setStatistic(playFabId, stat.statisticName, stat.value, stat.version);
  });

  // Default UserData. Here we form a default object for each key.
  const defaultUserData: { [key: string]: any } = {
    "ArenaMatches": [],
    "AvatarsData": [17],
    "ClubSmashLocal": {
      "WeekId": 276,
      "Defeats": 0,
      "Refreshies": 5,
      "BossTickets": 0,
      "SmashTickets": 0,
      "MilestoneBoss": 0,
      "MilestoneLocal": 0,
      "BossAttackBonus": 0,
      "PurchasedSmashTickets": 0,
      "CollectionDailyTickets": 0,
      "CollectionDailyTicketsBoss": 0,
      "DailyResultCollections": [],
      "_clubSmashPointsProxy": 0,
      "_smashTotalPointsProxy": 0,
      "Wins": [0, 0, 0, 0]
    },
    "CollectionData": {},
    "DailyGiftData": {
      "DayStreak": 1,
      "EventWelcomeLastCollected": 0,
      "EventDailyGiftRollTomorrow": 7,
      "EventDailyGiftRoll": 1,
      "EventDailyGiftLastCollected": 0,
      "DailyLast": 0,
      "DailyMilestone": 0,
      "XpMilestone": 0
    },
    "EventsData": {
      "MonthlyOrbs": { "StartedWith": 0, "EndingWeekId": 279, "Collections": [] },
      "MonthlySummons": { "StartedWith": 0, "EndingWeekId": 277, "Collections": [] },
      "MonthlyPokerChips": { "StartedWith": 0, "EndingWeekId": 276, "Collections": [] },
      "MonthlyMiscArena": { "StartedWith": 0, "EndingWeekId": 278, "Collections": [] },
      "MonthlyMiscFusion": { "StartedWith": 0, "EndingWeekId": 278, "Collections": [] },
      "MonthlyMiscShops": { "StartedWith": 0, "EndingWeekId": 278, "Collections": [] },
      "MonthlyMiscTavern4Stars": { "StartedWith": 0, "EndingWeekId": 278, "Collections": [] },
      "MonthlyMiscTavern5Stars": { "StartedWith": 0, "EndingWeekId": 278, "Collections": [] },
      "MonthlyMiscAll": { "StartedWith": 0, "EndingWeekId": 278, "Collections": [] },
      "ValuePackagePoker": { "StartedWith": 0, "EndingWeekId": 276, "Collections": [] },
      "OneTimeOnlyCustomSale": { "StartedWith": 0, "EndingWeekId": 276, "Collections": [] },
      "CarSmash": {
        "StartedWith": 0,
        "EndingWeekId": 276,
        "Collections": [],
        "ExtraData": {
          "DailyRewardIndex": 0,
          "CollectedGifts": [],
          "RewardRolls": [0, 0, 2, 3],
          "CritRolls": [2, 4, 8, 14, 16, 19],
          "CarRolls": [9, 6, 3],
          "HammersSent": [],
          "HammersCollected": [],
          "PerkIndex": 0,
          "Index": 0,
          "Hp": 100,
          "RollCount": 0,
          "MilestoneCollected": false,
          "NextRollData": { "RewardRolls": [2, 0, 0, 3], "CritRolls": [0, 7, 8], "CarRolls": [6, 3, 8] }
        }
      }
    },
    "FriendsData": {
      "CurrentWeek": 276,
      "Searchees": []
    },
    "GuildAchievements": {},
    "GuildSoloBoss": {
      "hp": 600000,
      "hpCap": 600000,
      "weekId": 276,
      "level": 0,
      "typeIndex": 2,
      "result": null,
      "minionIndex": 11,
      "soloMilestoneCollection": 0,
      "bossMilestoneCollection": 0,
      "purchaseIndex": 0,
      "collectedBosses": []
    },
    "HeroCardData": [69, 86, 72, 80],
    "HeroSlotsData": { "Slots": 100, "Purchases": 0 },
    // For KittyRolls, use arrays of fixed length.
    "KittyRolls": {
      "RecruitScrolls": Array(10).fill(37),
      "RecruitShardsBlue": Array(10).fill(19),
      "RecruitShardsPurple": Array(10).fill(37),
      "Tavern": Array(10).fill(209),
      "DojoSpin": Array(10).fill(4),
      "CasinoSpin": Array(10).fill(2),
      "EventMonopoly": Array(10).fill(50),
      "EventMonopolyCave": [2, 2, 7, 0, 7],
      "Materials": Array(10).fill(4),
      "ArtifactsPurple": [6, 7, 8, 7, 12, 14, 7, 14, 14, 14],
      "ArtifactsBlue": [3, 0, 3, 0, 1, 2, 2, 0, 1, 2, 3, 2, 1, 2, 1, 3, 4, 1, 2, 2, 3, 1, 2, 1, 0, 5, 3, 0, 2, 1, 5, 2, 2, 1, 1, 1, 4, 3, 2, 1, 0, 2, 3, 2, 1, 3, 0, 1, 1, 3],
      "MutagenRolls": [120305, 123003, 13207],
      "SuperMutagenRolls": [32110, 132011, 310211, 203111],
      "SlotsSpins": [24132253, 415053024, 320351350, 413350324, 435530304],
      "ArtifactsUltra": [11, 11, 16, 11, 11, 10, 16, 13, 15, 10],
      "ClubSmashRolls": [17302, 163240],
      "SmashBossRolls": [1, 402, 2],
      "CharmShardsRolls": [30, 20, 1],
      "RecruitOrbs": [25, 26, 1, 31, 8, 9, 11],
      "CharmSpins": [2, 1, 0, 12, 0, 0, 0, 0, 1, 1, 1, 2, 1, 10, 1, 0, 1, 1, 1, 11]
    },
    "KittyStats": {
      "Count_Summon": 0,
      "Count_Orbs": 0,
      "Count_Poker": 0,
      "Count_FriendCratesCollected": 0,
      "Count_ShopCollections": 0,
      "Count_ShopOpenings": 0,
      "Count_Tavern3Stars": 0,
      "Count_Tavern4Stars": 0,
      "Count_Tavern5Stars": 0,
      "Count_Fusions": 0,
      "Count_FusionsElite": 0,
      "Count_ArenaWins": 0,
      "Count_ArenaTickets": 0,
      "Count_GuildRolls": 0,
      "Count_MarketPurchases": 0,
      "Count_HeroSpawnPurple": 0,
      "Count_ArtifactSpawnPurple": 0,
      "Count_PurpleShards": 0,
      "Count_PizzaSpent": 0,
      "Count_Recruit": 0,
      "Count_GlobePurchases": 0,
      "BonusSummons": 0,
      "BonusOrbs": 0,
      "BonusShards": 0,
      "Guild_SoloDefeat": 0,
      "Guild_SoloDamage_v2": 0,
      "Guild_SoloSpawn": 0,
      "Guild_SoloLucky": 0,
      "Guild_Defeat": 0,
      "Guild_Slayer": 0,
      "Guild_MVP": 0,
      "Guild_RotatingCollections": 0,
      "Guild_LastCollectedWeek": 0,
      "Guild_DailyKeysData": 0,
      "Guild_WeeklyKeysData": 0,
      "GemsSpent": 0,
      "DailyPoints": 0,
      "DailyWelcomeBack": 0,
      "QuestsDailyCompletions": 0,
      "QuestsDailyCollections": 0,
      "QuestsWeeklyCompletions": 0,
      "QuestsWeeklyCollections": 0,
      "AchievementMilestonePoints": 0,
      "AchievementMilestoneProgress": 0,
      "GamePassLastDay": 0,
      "GamePassGranted": 0,
      "GamePassClaimed": 0,
      "PurchaseTier": 0,
      "OrbSelection": 0,
      "FreeValuePackageWeek": 0,
      "BeginnersQuests": 0,
      "VipDailyRoll": 4,
      "FriendCrateRoll": 0,
      "WeekIndex": 276,
      "FlashSaleTier": 0,
      "FirstLoginDay": Math.floor((Date.now() - new Date("2020-01-01").getTime()) / (1000 * 60 * 60 * 24)),
      "KittyBools": 0,
      "Unlocks": 0,
      "GoldBillions": 0,
      "HolidayCollection": 0,
      "TechnoLastCollection": 0,
      "TechnoRun": 0,
      "TechnoEvent": 0,
      "DesertCooldown": 0,
      "ArenaRefreshies": 0,
      "HardBoostSpins": 0,
      "HardBoostTopCollections": 0,
      "HardBoostTopCollectionsStart": 0,
      "HardBoostTopCollectionsLastDay": 0,
      "HardModeSpinsS": 0,
      "HardModeSpinsA": 0,
      "HardModeSpinsB": 0,
      "HardModeSpinsC": 0,
      "HardModeCardLastDay": 0,
      "HardModeCardCollection": 0,
      "HardModeCardLastDayPremium": 0,
      "HardModeCardCollectionPremium": 0,
      "HardModeUnlockDay": 0,
      "AscensionUnlockDay": 0,
      "ChatBadgeIndex": 0,
      "ClubSmashFinaleCollection": 0,
      "ClubSmashTotalTickets": 0,
      "ClubSmashTotalVulnerable": 0,
      "ClubSmashTotalEarnPoints": 0,
      "ClubSmashTotalBossTickets": 0,
      "OneDaySalePurchased": 0,
      "Best_GuildBossDamageTotal": 0,
      "Best_GuildSoloLevel": 0,
      "Best_GuildSoloDamage": 0,
      "Best_EventBattleship": 0,
      "Best_EventMonopoly": 0,
      "Best_EventCarSmash": 0,
      "Best_ArenaPoints": 0,
      "Best_TechnoPoints": 0,
      "Best_SlotsPoints": 0,
      "Best_GuildBossDmgOneFight": 0,
      "Best_SmashPoints": 0,
      "Best_GuildSoloLevel_NEW": 0,
      "Best_ClubSmashDamageTotal": 0,
      "Best_ClubSmashDmgOneFight": 0,
      "Guild_Best_CS_DamageFaction": 0,
      "Guild_CS_FactionWins_Red": 0,
      "Guild_CS_FactionWins_Green": 0,
      "Guild_CS_FactionWins_Yellow": 0,
      "Guild_CS_FactionWins_Blue": 0,
      "Guild_CS_FactionWins_Purple": 0,
      "SummonBadLuckCounter": 21,
      "OrbsBadLuckCounter": 7,
      "Guild_LastCollectedWeekRank": 0,
      "CampaignStuckDay": 0,
      "HardModeStuckDay": 0,
      "OrbsRecordElite": 0,
      "OrbsRecordUsed": 0,
      "BattleshipHits": 0,
      "BattleshipMisses": 0,
      "KittyRollLastCheck": 1091,
      "KittyRollLastCheckArti": 16,
      "LastUpdate": 297,
      "ArenaSize": 165354,
      "BestScoreDayIdCheck": 1928,
      "CALL_ID": 0,
      "DEV_WEEKOFFSET": 0,
      "ERROR_CHECK_WEEK": 0,
      "BuggyFixWeek": 275,
      "_bt64": 0,
      "_bd64": 0,
      "_sd64": 0,
      "_bs64": 0,
      "_dm64": 0,
      "_bb64": 0,
      "_cd64": 0,
      "_bc64": 0,
      "_cx64": 0,
      "_bx64": 0,
      "_d_64": 0
    },
    // Virtual Currency defaults
    "UserVirtualCurrency": {
      "A0": 0,
      "A1": 0,
      "A2": 0,
      "AC": 0,
      "AD": 0,
      "AS": 0,
      "AT": 10,
      "BH": 0,
      "BS": 0,
      "BT": 0,
      "C0": 0,
      "C2": 0,
      "CB": 0,
      "CS": 0,
      "DI": 0,
      "EH": 0,
      "FB": 0,
      "GC": 0,
      "GE": 500,
      "GK": 0,
      "GM": 0,
      "GO": 5000,
      "GS": 0,
      "GX": 0,
      "H0": 0,
      "H1": 0,
      "HC": 0,
      "IA": 0,
      "M0": 0,
      "OR": 0,
      "OZ": 100,
      "PC": 5,
      "RE": 0,
      "RO": 0,
      "SC": 5,
      "SI": 5000,
      "SM": 0,
      "ST": 0,
      "T1": 0,
      "T2": 0,
      "TC": 0,
      "TI": 40,
      "TR": 10,
      "TT": 0,
      "TY": 0,
      "VI": 0,
      "XP": 0
    }
  };

  // Store default user data. Here we iterate over each key in the defaultUserData object.
  Object.keys(defaultUserData).forEach(key => {
    // If the value is already a string, store as is; otherwise JSON-stringify it.
    const dataValue = typeof defaultUserData[key] === "string"
      ? defaultUserData[key]
      : JSON.stringify(defaultUserData[key]);
    setUserData(playFabId, key, dataValue);
  });

  // Set default virtual currency values.
  const defaultVirtualCurrency = {
    "A0": 0,
    "A1": 0,
    "A2": 0,
    "AC": 0,
    "AD": 0,
    "AS": 0,
    "AT": 10,
    "BH": 0,
    "BS": 0,
    "BT": 0,
    "C0": 0,
    "C2": 0,
    "CB": 0,
    "CS": 0,
    "DI": 0,
    "EH": 0,
    "FB": 0,
    "GC": 0,
    "GE": 500,
    "GK": 0,
    "GM": 0,
    "GO": 5000,
    "GS": 0,
    "GX": 0,
    "H0": 0,
    "H1": 0,
    "HC": 0,
    "IA": 0,
    "M0": 0,
    "OR": 0,
    "OZ": 100,
    "PC": 5,
    "RE": 0,
    "RO": 0,
    "SC": 5,
    "SI": 5000,
    "SM": 0,
    "ST": 0,
    "T1": 0,
    "T2": 0,
    "TC": 0,
    "TI": 40,
    "TR": 10,
    "TT": 0,
    "TY": 0,
    "VI": 0,
    "XP": 0
  };
  
  Object.keys(defaultVirtualCurrency).forEach(currency => {
    setCurrency(playFabId, currency, defaultVirtualCurrency[currency as keyof typeof defaultVirtualCurrency]);
  });
}
